"""create paid beta production schema

Revision ID: 20260715_0001
Revises:
Create Date: 2026-07-15
"""
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260715_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_daily_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('provider_cost_usd', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('provider_latency_ms_total', sa.Integer(), nullable=False),
    sa.Column('provider_latency_ms_max', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms_total', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms_max', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'environment', 'model', 'state', name='uq_operational_daily_dimension')
    )
    op.create_table('plans',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('price_usd_cents', sa.Integer(), nullable=False),
    sa.Column('paddle_product_id', sa.String(length=100), nullable=True),
    sa.Column('paddle_price_id', sa.String(length=100), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('per_minute_limit', sa.Integer(), nullable=False),
    sa.Column('per_day_limit', sa.Integer(), nullable=False),
    sa.Column('concurrent_limit', sa.Integer(), nullable=False),
    sa.Column('accuracy_enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('paddle_price_id'),
    sa.UniqueConstraint('paddle_product_id')
    )
    now = datetime.now(UTC)
    plans = sa.table(
        'plans',
        sa.column('code', sa.String),
        sa.column('display_name', sa.String),
        sa.column('price_usd_cents', sa.Integer),
        sa.column('paddle_product_id', sa.String),
        sa.column('paddle_price_id', sa.String),
        sa.column('monthly_quota', sa.Integer),
        sa.column('per_minute_limit', sa.Integer),
        sa.column('per_day_limit', sa.Integer),
        sa.column('concurrent_limit', sa.Integer),
        sa.column('accuracy_enabled', sa.Boolean),
        sa.column('active', sa.Boolean),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        plans,
        [
            {
                'code': 'free',
                'display_name': 'Free',
                'price_usd_cents': 0,
                'paddle_product_id': None,
                'paddle_price_id': None,
                'monthly_quota': 0,
                'per_minute_limit': 0,
                'per_day_limit': 0,
                'concurrent_limit': 0,
                'accuracy_enabled': False,
                'active': True,
                'updated_at': now,
            },
            {
                'code': 'pro_beta',
                'display_name': 'Pro Beta',
                'price_usd_cents': 499,
                'paddle_product_id': None,
                'paddle_price_id': None,
                'monthly_quota': 100,
                'per_minute_limit': 5,
                'per_day_limit': 30,
                'concurrent_limit': 2,
                'accuracy_enabled': True,
                'active': True,
                'updated_at': now,
            },
        ],
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('google_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized'),
    sa.UniqueConstraint('google_subject')
    )
    op.create_table('webhook_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_state', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_webhook_unprocessed', 'webhook_events', ['processing_state', 'occurred_at'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_expires_at'), 'audit_events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_identifier', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash'),
    sa.UniqueConstraint('user_id', 'device_identifier', name='uq_auth_session_device')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('beta_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('activation_user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activation_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('paddle_customer_id', sa.String(length=100), nullable=False),
    sa.Column('paddle_subscription_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=False),
    sa.Column('price_id', sa.String(length=100), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_change', sa.String(length=32), nullable=True),
    sa.Column('scheduled_change_effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paddle_customer_id'),
    sa.UniqueConstraint('paddle_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('usage_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quota_limit', sa.Integer(), nullable=False),
    sa.Column('reserved_units', sa.Integer(), nullable=False),
    sa.Column('consumed_units', sa.Integer(), nullable=False),
    sa.Column('actual_provider_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_start', 'period_end', name='uq_usage_user_period')
    )
    op.create_index('ix_usage_user_period', 'usage_periods', ['user_id', 'period_end'], unique=False)
    op.create_table('extraction_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('usage_period_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('input_hmac', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('quota_reserved', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('provider_generation_id', sa.String(length=255), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_cost_usd', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('provider_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('encrypted_result_envelope', sa.LargeBinary(), nullable=True),
    sa.Column('result_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usage_period_id'], ['usage_periods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_extraction_idempotency')
    )
    op.create_index('ix_extraction_expiring_result', 'extraction_requests', ['result_expires_at', 'state'], unique=False)
    op.create_index(op.f('ix_extraction_requests_result_expires_at'), 'extraction_requests', ['result_expires_at'], unique=False)
    op.create_index(op.f('ix_extraction_requests_state'), 'extraction_requests', ['state'], unique=False)
    op.create_index('ix_extraction_user_created', 'extraction_requests', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extraction_user_created', table_name='extraction_requests')
    op.drop_index(op.f('ix_extraction_requests_state'), table_name='extraction_requests')
    op.drop_index(op.f('ix_extraction_requests_result_expires_at'), table_name='extraction_requests')
    op.drop_index('ix_extraction_expiring_result', table_name='extraction_requests')
    op.drop_table('extraction_requests')
    op.drop_index('ix_usage_user_period', table_name='usage_periods')
    op.drop_table('usage_periods')
    op.drop_table('subscriptions')
    op.drop_table('beta_invites')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_expires_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_webhook_unprocessed', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_table('operational_daily_stats')
    # ### end Alembic commands ###
